i18n.gettext(
  'clipboard-x',
  install_dir: extension_dir / 'locale',
  languages: [
    'ar',
    'bg',
    'ca',
    'cs',
    'de',
    'el',
    'es',
    'eu',
    'fa',
    'fi',
    'fr_FR',
    'hu',
    'it',
    'ja',
    'kn',
    'ko',
    'nl',
    'oc',
    'pl',
    'pt_BR',
    'ru',
    'sk',
    'tr',
    'uk',
    'zh_CN',
  ],
  preset: 'glib',
)
